module.exports =
    {
        "USD": "ABD DOLARI",
        "EUR": "EURO",
        "GBP": "İNGİLİZ STERLİNİ",
        "CHF": "İSVİÇRE FRANGI",
        "CAD": "KANADA DOLARI",
        "RUB": "RUS RUBLESİ",
        "AED": "",
        "AUD": "AVUSTRALYA DOLARI",
        "DKK": "DANİMARKA KRONU",
        "SEK": "İSVEÇ KRONU",
        "NOK": "NORVEÇ KRONU",
        "JPY": "JAPON YENİ",
        "KWD": "KUVEYT DİNARI",
        "ZAR": "",
        "BHD": "",
        "LYD": "",
        "SAR": "SUUDİ ARABİSTAN RİYALİ",
        "IQD": "",
        "ILS": "",
        "IRR": "İRAN RİYALİ",
        "INR": "",
        "MXN": "",
        "HUF": "",
        "NZD": "",
        "BRL": "",
        "IDR": "",
        "CSK": "",
        "PLN": "",
        "RON": "RUMEN LEYİ",
        "CNY": "ÇİN YUANI",
        "ARS": "",
        "ALL": "",
        "AZN": "",
        "BAM": "",
        "CLP": "",
        "COP": "",
        "CRC": "",
        "DZD": "",
        "EGP": "",
        "HKD": "",
        "HRK": "",
        "ISK": "",
        "JOD": "",
        "KRW": "",
        "KZT": "",
        "LBP": "",
        "LKR": "",
        "MAD": "",
        "MDL": "",
        "MKD": "",
        "MYR": "",
        "OMR": "",
        "PEN": "",
        "PHP": "",
        "PKR": "",
        "QAR": "KATAR RİYALİ",
        "RSD": "",
        "SGD": "",
        "SYP": "",
        "THB": "",
        "TWD": "",
        "UAH": "",
        "UYU": "",
        "GEL": "",
        "TND": "",
        "SEPET KUR": "SEPET KUR",
        "BGN": "BULGAR LEVASI",
        "ons": "Ons Altın",
        "gram-altin": "Gram Altın",
        "ceyrek-altin": "Çeyrek Altın",
        "yarim-altin": "Yarım Altın",
        "tam-altin": "Tam Altın",
        "cumhuriyet-altini": "Cumhuriyet Altını",
        "ata-altin": "Ata Altın",
        "resat-altin": "Reşat Altın",
        "hamit-altin": "Hamit Altın",
        "ikibucuk-altin": "İkibuçuk Altın",
        "gremse-altin": "Gremse Altın",
        "besli-altin": "Beşli Altın",
        "14-ayar-altin": "14 Ayar Altın",
        "18-ayar-altin": "18 Ayar Altın",
        "22-ayar-bilezik": "22 Ayar Bilezik",
        "gumus": "Gümüş"
    }